"use client";

import Link from 'next/link';
import { useState, useEffect } from 'react';

const prenupSchema = [
  {
    category: "Financial Asset Division",
    id: "assets",
    items: [
      { id: "separate_prop", label: "Separate property identification and protection", tooltip: "List assets owned before marriage that should remain separate." },
      { id: "marital_prop_def", label: "Marital property definition and classification", tooltip: "How will property acquired during marriage be classified?" },
      { id: "appreciation_sep", label: "Appreciation of separate property", tooltip: "Does increase in value of separate property become marital property?" },
      { id: "commingling_rules", label: "Commingling rules", tooltip: "What happens when separate and marital funds mix?" },
      { id: "investment_accts", label: "Investment accounts", tooltip: "Brokerage, retirement, crypto, private equity treatment." },
      { id: "real_estate", label: "Real estate", tooltip: "Primary residence, vacation homes, rental properties, land." },
      { id: "business_interests", label: "Business interests", tooltip: "Valuation methods, growth attribution, buyout terms." },
      { id: "intellectual_prop", label: "Intellectual property", tooltip: "Copyrights, patents, trademarks, royalties." },
      { id: "stock_options", label: "Stock options, RSUs", tooltip: "Deferred compensation and equity grants." },
      { id: "inheritances", label: "Inheritances", tooltip: "Protection of expected future inheritances." },
      { id: "family_gifts", label: "Family gifts and heirlooms", tooltip: "Documentation and exclusion clauses." },
      { id: "collectibles", label: "Art, collectibles, jewelry", tooltip: "High-value personal property treatment." },
      { id: "digital_assets", label: "Digital assets", tooltip: "Domain names, social media, NFTs, online businesses." },
      { id: "trust_interests", label: "Trust interests", tooltip: "Beneficiary rights and distribution timing." }
    ]
  },
  {
    category: "Debt & Liability Allocation",
    id: "debts",
    items: [
      { id: "premarital_debt", label: "Pre-marital debt responsibility", tooltip: "Student loans, credit cards, mortgages acquired before marriage." },
      { id: "marital_debt_def", label: "Marital debt definition", tooltip: "Joint liability parameters for debts acquired during marriage." },
      { id: "credit_card_policy", label: "Credit card usage policies", tooltip: "Spending limits and approval requirements." },
      { id: "cosigning_restrictions", label: "Co-signing restrictions", tooltip: "Rules for co-signing loans post-marriage." },
      { id: "business_debt", label: "Business debt separation", tooltip: "Separating business debt from personal liability." },
      { id: "tax_debt", label: "Tax debt allocation", tooltip: "Liability for past or future tax debts." },
      { id: "lawsuit_liability", label: "Lawsuit liability protection", tooltip: "Legal judgment or lawsuit liability protection." },
      { id: "medical_debt", label: "Medical debt responsibility", tooltip: "Insurance coordination and responsibility." },
      { id: "guarantee_limits", label: "Guarantee liability limitations", tooltip: "Limits on personal guarantees." },
      { id: "debt_payoff", label: "Debt payoff timelines", tooltip: "Expectations for paying off existing debts." }
    ]
  },
  {
    category: "Income & Earnings During Marriage",
    id: "income",
    items: [
      { id: "salary_treatment", label: "Salary and bonuses treatment", tooltip: "How will active income be classified?" },
      { id: "passive_income", label: "Passive income treatment", tooltip: "Dividends, interest, rental income, royalties." },
      { id: "side_hustle", label: "Side hustle income", tooltip: "Freelance or side business income classification." },
      { id: "career_advancement", label: "Career advancement earnings", tooltip: "Promotions, raises, new opportunities." },
      { id: "professional_practice", label: "Professional practice income", tooltip: "Law, medicine, consulting practice earnings." },
      { id: "influencer_earnings", label: "Influencer/Sports earnings", tooltip: "Branding rights and social media income." },
      { id: "book_deals", label: "Book deals and speaking fees", tooltip: "Appearance income and royalties." },
      { id: "income_from_sep", label: "Income from separate property", tooltip: "Earnings generated by separate assets." },
      { id: "non_financial_contrib", label: "Non-financial support credits", tooltip: "Homemaking, childcare contributions." },
      { id: "income_disparity", label: "Income disparity adjustments", tooltip: "Equalization mechanisms for different earnings." }
    ]
  },
  {
    category: "Spousal Support (Alimony) Provisions",
    id: "support",
    items: [
      { id: "waiver_support", label: "Waiver of spousal support", tooltip: "Full, partial, or conditional waiver." },
      { id: "duration_caps", label: "Duration caps or sunset clauses", tooltip: "Limits on how long support is paid." },
      { id: "amount_formulas", label: "Amount formulas", tooltip: "Percentage of income or fixed sum." },
      { id: "trigger_events", label: "Trigger events", tooltip: "Job loss, disability, relocation." },
      { id: "termination_clauses", label: "Termination clauses", tooltip: "Cohabitation or remarriage termination." },
      { id: "review_procedures", label: "Review/modification procedures", tooltip: "Timelines for reviewing support." },
      { id: "career_sacrifice", label: "Career sacrifice reimbursement", tooltip: "Compensation for educational support." },
      { id: "health_insurance_post", label: "Health insurance post-separation", tooltip: "Continuation of coverage." },
      { id: "tax_treatment_support", label: "Tax treatment allocation", tooltip: "Who claims support on taxes." },
      { id: "enforcement_mech", label: "Enforcement mechanisms", tooltip: "Jurisdiction for disputes." }
    ]
  },
  {
    category: "Retirement & Long-Term Savings",
    id: "retirement",
    items: [
      { id: "retirement_div", label: "401(k)/IRA division methodology", tooltip: "How retirement accounts will be split." },
      { id: "pension_plans", label: "Pension plans valuation", tooltip: "QDRO requirements and survivor benefits." },
      { id: "military_retirement", label: "Military retirement pay", tooltip: "VA benefit considerations." },
      { id: "social_security_coord", label: "Social Security coordination", tooltip: "Waiver limitations." },
      { id: "hsa_ownership", label: "HSA/FSA account ownership", tooltip: "Contribution rules." },
      { id: "annuities", label: "Annuities and insurance products", tooltip: "Linked savings products." },
      { id: "vesting_schedules", label: "Vesting schedules treatment", tooltip: "Unvested benefits treatment." },
      { id: "early_withdrawal", label: "Early withdrawal penalties", tooltip: "Tax consequence allocation." },
      { id: "post_divorce_contrib", label: "Post-divorce contribution rights", tooltip: "To pre-marital accounts." },
      { id: "beneficiary_override", label: "Beneficiary override procedures", tooltip: "Changing designations." }
    ]
  },
  {
    category: "Real Estate & Housing",
    id: "realestate",
    items: [
      { id: "primary_res", label: "Primary residence ownership", tooltip: "Buyout terms and sale triggers." },
      { id: "vacation_prop", label: "Vacation property usage", tooltip: "Expense allocation." },
      { id: "rental_income_dist", label: "Rental property income", tooltip: "Distribution and management rights." },
      { id: "mortgage_resp", label: "Mortgage responsibility", tooltip: "Equity buildup credit." },
      { id: "home_improve", label: "Home improvement splits", tooltip: "Value appreciation splits." },
      { id: "refinancing_consent", label: "Refinancing consent", tooltip: "Liability shifts." },
      { id: "relocation_sale", label: "Relocation sale protocols", tooltip: "Job transfer protocols." },
      { id: "cohabitation_agreements", label: "Co-habitation agreements", tooltip: "If marriage doesn't occur." },
      { id: "refusal_right", label: "Right of first refusal", tooltip: "For property purchases." },
      { id: "partition_actions", label: "Partition actions", tooltip: "Forced sale limitations." }
    ]
  },
  {
    category: "Business & Professional Interests",
    id: "business",
    items: [
      { id: "business_valuation", label: "Business valuation method", tooltip: "Fixed formula, appraisal, etc." },
      { id: "growth_attribution", label: "Growth attribution", tooltip: "Marital effort vs. separate capital." },
      { id: "buy_sell_agreements", label: "Buy-sell agreements", tooltip: "Triggered by divorce or death." },
      { id: "management_rights", label: "Management rights", tooltip: "Decision-making authority." },
      { id: "non_compete", label: "Non-compete restrictions", tooltip: "Post-divorce restrictions." },
      { id: "client_list_prot", label: "Client list protection", tooltip: "Goodwill and trade secrets." },
      { id: "partnership_align", label: "Partnership alignment", tooltip: "Shareholder agreement alignment." },
      { id: "succession_planning", label: "Succession planning", tooltip: "Integration with marital agreement." },
      { id: "spousal_employment", label: "Spousal employment", tooltip: "Compensation and role." },
      { id: "ip_developed", label: "IP developed during marriage", tooltip: "Ownership split." }
    ]
  },
  {
    category: "Lifestyle & Non-Financial",
    id: "lifestyle",
    items: [
      { id: "infidelity_clauses", label: "Infidelity clauses", tooltip: "Financial consequences (limited enforceability)." },
      { id: "appearance_incentives", label: "Appearance incentives", tooltip: "Weight gain or health (rarely enforceable)." },
      { id: "social_media_conduct", label: "Social media conduct", tooltip: "Privacy expectations." },
      { id: "religious_upbringing", label: "Religious practice/upbringing", tooltip: "Cultural observance agreements." },
      { id: "relocation_restrictions", label: "Relocation restrictions", tooltip: "Geographic consent requirements." },
      { id: "pet_custody", label: "Pet custody and care", tooltip: "Visitation protocols." },
      { id: "household_alloc", label: "Household allocations", tooltip: "Responsibility splits (clarifying only)." },
      { id: "counseling_req", label: "Counseling requirements", tooltip: "Before filing for divorce." },
      { id: "dispute_resolution", label: "Dispute resolution", tooltip: "Arbitration vs. litigation." },
      { id: "confidentiality", label: "Confidentiality clauses", tooltip: "Non-disparagement clauses." }
    ]
  },
  {
    category: "Estate Planning Integration",
    id: "estate",
    items: [
      { id: "waiver_elective_share", label: "Waiver of elective share", tooltip: "Statutory inheritance rights." },
      { id: "life_ins_beneficiary", label: "Life insurance beneficiary", tooltip: "Policy ownership." },
      { id: "trust_funding", label: "Trust funding protocols", tooltip: "Post-marriage amendments." },
      { id: "right_to_reside", label: "Right to reside in home", tooltip: "After spouse's death." },
      { id: "personal_prop_dist", label: "Personal property dist.", tooltip: "Jewelry, art, heirlooms." },
      { id: "digital_asset_legacy", label: "Digital asset legacy", tooltip: "Passwords, accounts." },
      { id: "funeral_pref", label: "Funeral and burial pref.", tooltip: "Documentation." },
      { id: "organ_donation", label: "Organ donation", tooltip: "Medical directive coordination." },
      { id: "guardianship_pref", label: "Guardianship pref.", tooltip: "For minor children (non-binding)." },
      { id: "charitable_giving", label: "Charitable giving", tooltip: "Family foundation roles." }
    ]
  },
  {
    category: "Children & Family Considerations",
    id: "children",
    items: [
      { id: "prior_child_support", label: "Prior child support", tooltip: "Acknowledgment of existing obligations." },
      { id: "stepparent_role", label: "Stepparent role", tooltip: "Financial boundaries." },
      { id: "education_funding", label: "Education funding", tooltip: "529 plans, private school." },
      { id: "extracurricular_alloc", label: "Extracurricular alloc.", tooltip: "Expense allocation." },
      { id: "stepchild_healthcare", label: "Stepchild healthcare", tooltip: "Insurance coverage." },
      { id: "ex_communication", label: "Communication with exes", tooltip: "Regarding children." },
      { id: "holiday_scheduling", label: "Holiday scheduling", tooltip: "Frameworks (non-binding)." },
      { id: "college_savings", label: "College savings", tooltip: "Contribution expectations." },
      { id: "inheritance_children", label: "Inheritance for children", tooltip: "Biological vs. stepchildren." },
      { id: "surrogacy_costs", label: "Surrogacy/Adoption costs", tooltip: "Allocation." }
    ]
  },
  {
    category: "Tax Planning & Coordination",
    id: "tax",
    items: [
      { id: "filing_status", label: "Filing status election", tooltip: "Joint vs. separate returns." },
      { id: "tax_liability", label: "Tax liability allocation", tooltip: "For joint returns." },
      { id: "refund_dist", label: "Refund distribution", tooltip: "Methodology." },
      { id: "state_residency", label: "State residency planning", tooltip: "For tax optimization." },
      { id: "capital_gains", label: "Capital gains treatment", tooltip: "Asset transfers between spouses." },
      { id: "gift_tax", label: "Gift tax exclusion", tooltip: "Interspousal transfers." },
      { id: "estate_tax", label: "Estate tax marital deduction", tooltip: "Portability elections." },
      { id: "international_tax", label: "International tax residency", tooltip: "Treaty considerations." },
      { id: "deduction_alloc", label: "Deduction allocation", tooltip: "Mortgage interest, charitable gifts." },
      { id: "irs_audit", label: "IRS audit responsibility", tooltip: "Cost-sharing protocols." }
    ]
  },
  {
    category: "International & Cross-Border Elements",
    id: "international",
    items: [
      { id: "governing_law", label: "Governing law selection", tooltip: "Which jurisdiction applies." },
      { id: "enforcement_foreign", label: "Enforcement in foreign jurisdictions", tooltip: "Strategy." },
      { id: "currency_fluctuation", label: "Currency fluctuation", tooltip: "Protections for asset valuation." },
      { id: "foreign_asset_disclosure", label: "Foreign asset disclosure", tooltip: "Valuation protocols." },
      { id: "dual_citizenship", label: "Dual citizenship implications", tooltip: "Property and inheritance." },
      { id: "intl_relocation", label: "International relocation", tooltip: "Financial adjustments." },
      { id: "apostille_req", label: "Apostille requirements", tooltip: "Document validity." },
      { id: "translation_req", label: "Translation requirements", tooltip: "Multilingual agreements." },
      { id: "conflict_of_laws", label: "Conflict of laws analysis", tooltip: "For key provisions." },
      { id: "exit_strategy", label: "Exit strategy", tooltip: "Divorce jurisdiction and enforcement." }
    ]
  },
  {
    category: "Contingency & Trigger Events",
    id: "contingency",
    items: [
      { id: "sunset_clause", label: "Duration of agreement", tooltip: "Perpetual, sunset, or review dates." },
      { id: "material_change", label: "Material change triggers", tooltip: "Birth of child, disability, job loss." },
      { id: "infidelity_consequences", label: "Infidelity or misconduct consequences", tooltip: "Financial consequences if enforceable." },
      { id: "incapacity_protocols", label: "Incapacity protocols", tooltip: "Cognitive decline protocols." },
      { id: "bankruptcy_prot", label: "Bankruptcy protections", tooltip: "Financial distress protections." },
      { id: "career_change_adj", label: "Career change adjustments", tooltip: "Sabbatical financial adjustments." },
      { id: "reconciliation_prov", label: "Reconciliation provisions", tooltip: "After separation." },
      { id: "death_termination", label: "Death of either spouse", tooltip: "Agreement termination or survival." },
      { id: "mutual_amendment", label: "Mutual amendment procedures", tooltip: "Execution requirements." },
      { id: "severability_clause", label: "Severability clause", tooltip: "To preserve enforceable portions." }
    ]
  },
  {
    category: "Process & Procedural Safeguards",
    id: "process",
    items: [
      { id: "full_disclosure", label: "Full financial disclosure", tooltip: "Documentation standards." },
      { id: "independent_counsel", label: "Independent legal counsel", tooltip: "Strongly recommended for both parties." },
      { id: "timing_execution", label: "Timing of execution", tooltip: "Well before wedding to avoid duress." },
      { id: "notarization_req", label: "Notarization requirements", tooltip: "Per jurisdiction." },
      { id: "voluntary_execution", label: "Voluntary execution affirmation", tooltip: "Capacity verification." },
      { id: "translation_services", label: "Translation services", tooltip: "If parties speak different languages." },
      { id: "cooling_off", label: "Cooling-off period", tooltip: "Before signing." },
      { id: "storage_accessibility", label: "Storage and accessibility", tooltip: "Of executed agreement." },
      { id: "periodic_review", label: "Periodic review schedule", tooltip: "e.g., every 5 years." },
      { id: "integration_clause", label: "Integration clause", tooltip: "Confirming this is complete agreement." }
    ]
  }
];

export default function PrenupPage() {
  const [activeTab, setActiveTab] = useState<'bride' | 'groom'>('bride');
  const [brideAnswers, setBrideAnswers] = useState<Record<string, string>>({});
  const [groomAnswers, setGroomAnswers] = useState<Record<string, string>>({});
  const [expandedCategories, setExpandedCategories] = useState<string[]>([prenupSchema[0].id]);
  const [loading, setLoading] = useState(true);
  const [generatedPrompt, setGeneratedPrompt] = useState('');

  useEffect(() => {
    async function fetchData() {
      try {
        const res = await fetch('/api/legal/prenup');
        const data = await res.json();
        if (data && !data.error) {
          setBrideAnswers(data.brideAnswers || {});
          setGroomAnswers(data.groomAnswers || {});
        }
      } catch (error) {
        console.error('Failed to fetch prenup data:', error);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  async function saveData(updatedBride: any, updatedGroom: any) {
    try {
      await fetch('/api/legal/prenup', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brideAnswers: updatedBride, groomAnswers: updatedGroom })
      });
    } catch (error) {
      console.error('Failed to save prenup data:', error);
    }
  }

  const updateAnswer = (id: string, value: string) => {
    if (activeTab === 'bride') {
      setBrideAnswers(prev => {
        const updated = { ...prev, [id]: value };
        saveData(updated, groomAnswers);
        return updated;
      });
    } else {
      setGroomAnswers(prev => {
        const updated = { ...prev, [id]: value };
        saveData(brideAnswers, updated);
        return updated;
      });
    }
  };

  const toggleCategory = (id: string) => {
    setExpandedCategories(prev =>
      prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]
    );
  };

  const generatePrompt = () => {
    let prompt = `Act as a family law attorney. I need a standard outline or draft for a prenuptial agreement based on the following information provided by both parties.

BRIDE'S STANCE & ASSETS:
`;
    prenupSchema.forEach(section => {
      prompt += `\n### ${section.category}\n`;
      section.items.forEach(item => {
        const answer = brideAnswers[item.id];
        if (answer) {
          prompt += `- **${item.label}**: ${answer}\n`;
        }
      });
    });

    prompt += `\nGROOM'S STANCE & ASSETS:\n`;
    prenupSchema.forEach(section => {
      prompt += `\n### ${section.category}\n`;
      section.items.forEach(item => {
        const answer = groomAnswers[item.id];
        if (answer) {
          prompt += `- **${item.label}**: ${answer}\n`;
        }
      });
    });

    prompt += `\nPlease generate a comprehensive and fair outline for a prenuptial agreement that addresses all the points mentioned above. Include standard legal clauses for the jurisdiction if applicable, and add a clear disclaimer that this is a sample draft and not legal advice.`;

    setGeneratedPrompt(prompt);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedPrompt);
    alert('Prompt copied to clipboard!');
  };

  if (loading) {
    return <div className="container">Loading prenup builder...</div>;
  }

  return (
    <div style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
      <Link href="/legal" className="btn btn-secondary" style={{ marginBottom: '1rem', display: 'inline-block' }}>← Back to Legal Hub</Link>
      
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '2.5rem', marginBottom: '0.5rem', color: 'var(--accent-primary)' }}>Prenuptial Agreement Builder</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>Answer detailed questions for both parties to generate a comprehensive AI prompt.</p>
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: '1rem', marginBottom: '2rem', borderBottom: '1px solid var(--neutral-gray)' }}>
        <button 
          onClick={() => setActiveTab('bride')}
          style={{ 
            padding: '1rem 2rem', 
            border: 'none', 
            background: 'none', 
            cursor: 'pointer',
            fontSize: '1.1rem',
            fontWeight: activeTab === 'bride' ? 'bold' : 'normal',
            color: activeTab === 'bride' ? 'var(--accent-primary)' : 'var(--text-secondary)',
            borderBottom: activeTab === 'bride' ? '2px solid var(--accent-primary)' : 'none'
          }}
        >
          Bride's Questionnaire
        </button>
        <button 
          onClick={() => setActiveTab('groom')}
          style={{ 
            padding: '1rem 2rem', 
            border: 'none', 
            background: 'none', 
            cursor: 'pointer',
            fontSize: '1.1rem',
            fontWeight: activeTab === 'groom' ? 'bold' : 'normal',
            color: activeTab === 'groom' ? 'var(--accent-primary)' : 'var(--text-secondary)',
            borderBottom: activeTab === 'groom' ? '2px solid var(--accent-primary)' : 'none'
          }}
        >
          Groom's Questionnaire
        </button>
      </div>

      {/* Form Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        {/* Left Column: Form */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {prenupSchema.map(section => {
            const isExpanded = expandedCategories.includes(section.id);
            return (
              <div key={section.id} className="card" style={{ padding: '1.5rem' }}>
                <div 
                  style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }}
                  onClick={() => toggleCategory(section.id)}
                >
                  <h3 style={{ fontSize: '1.1rem', fontFamily: 'var(--font-serif)', color: 'var(--text-primary)' }}>{section.category}</h3>
                  <span style={{ fontSize: '1.2rem', transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}>
                    ▼
                  </span>
                </div>

                <div style={{ 
                  marginTop: '1rem', 
                  maxHeight: isExpanded ? '2000px' : '0', 
                  overflow: 'hidden', 
                  transition: 'maxHeight 0.3s ease, opacity 0.3s ease',
                  opacity: isExpanded ? 1 : 0
                }}>
                  {section.items.map(item => (
                    <div key={item.id} style={{ marginBottom: '1rem' }}>
                      <label style={{ fontSize: '0.85rem', fontWeight: 'bold', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                        {item.label}
                        <span title={item.tooltip} style={{ cursor: 'help', color: 'var(--accent-primary)' }}>ⓘ</span>
                      </label>
                      <input 
                        type="text" 
                        value={(activeTab === 'bride' ? brideAnswers[item.id] : groomAnswers[item.id]) || ''} 
                        onChange={(e) => updateAnswer(item.id, e.target.value)}
                        placeholder="N/A or details..."
                        style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid var(--neutral-gray)', marginTop: '0.25rem', fontSize: '0.9rem' }}
                      />
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
          
          {/* Informational Cards */}
          <div className="card" style={{ padding: '1.5rem', background: 'rgba(220, 53, 69, 0.05)', border: '1px solid rgba(220, 53, 69, 0.2)', marginBottom: '1rem' }}>
            <h3 style={{ fontSize: '1.1rem', fontFamily: 'var(--font-serif)', color: '#dc3545', marginBottom: '1rem' }}>🚫 What Typically CANNOT Be Included</h3>
            <ul style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', paddingLeft: '1.2rem', lineHeight: '1.6' }}>
              <li>Child custody or visitation arrangements</li>
              <li>Child support amounts or waivers</li>
              <li>Non-financial personal behavior mandates (e.g., household chores)</li>
              <li>Waiver of rights to report criminal activity or domestic violence</li>
              <li>Provisions encouraging divorce or penalizing reconciliation</li>
              <li>Unconscionable terms that leave one spouse destitute</li>
              <li>Illegal activities or conditions violating public policy</li>
            </ul>
          </div>

          <div className="card" style={{ padding: '1.5rem', background: 'rgba(40, 167, 69, 0.05)', border: '1px solid rgba(40, 167, 69, 0.2)' }}>
            <h3 style={{ fontSize: '1.1rem', fontFamily: 'var(--font-serif)', color: '#28a745', marginBottom: '1rem' }}>💡 Practical Implementation Tips</h3>
            <ul style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', paddingLeft: '1.2rem', lineHeight: '1.6', listStyleType: 'none' }}>
              <li>✅ Start the conversation early—ideally 6+ months before the wedding</li>
              <li>✅ Hire separate, experienced family law attorneys for each party</li>
              <li>✅ Prepare comprehensive asset/debt schedules with documentation</li>
              <li>✅ Be transparent: full disclosure strengthens enforceability</li>
              <li>✅ Keep the agreement balanced: extreme one-sided terms risk invalidation</li>
              <li>✅ Revisit after major life events: birth, inheritance, career shift</li>
            </ul>
          </div>
        </div>

        {/* Right Column: Prompt Generator */}
        <div style={{ position: 'sticky', top: '2rem', height: 'fit-content' }}>
          <div className="card" style={{ padding: '1.5rem' }}>
            <h3 style={{ fontSize: '1.2rem', fontFamily: 'var(--font-serif)', marginBottom: '1rem', color: 'var(--accent-primary)' }}>🤖 Master Prompt Generator</h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>
              Once both parties have filled out their sections, click below to generate a comprehensive prompt for your AI.
            </p>
            
            <button 
              className="btn btn-primary" 
              onClick={generatePrompt}
              style={{ width: '100%', marginBottom: '1rem' }}
            >
              Generate Master Prompt
            </button>

            <div style={{ background: 'var(--bg-secondary)', padding: '1rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--neutral-gray)', position: 'relative', minHeight: '300px' }}>
              {generatedPrompt ? (
                <>
                  <p style={{ fontSize: '0.8rem', color: 'var(--text-primary)', whiteSpace: 'pre-wrap', marginRight: '2rem' }}>{generatedPrompt}</p>
                  <button 
                    onClick={copyToClipboard}
                    style={{ position: 'absolute', top: '0.5rem', right: '0.5rem', padding: '0.25rem 0.5rem', fontSize: '0.8rem', background: 'white', border: '1px solid var(--neutral-gray)', borderRadius: '4px', cursor: 'pointer' }}
                  >
                    📋 Copy
                  </button>
                </>
              ) : (
                <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textAlign: 'center', marginTop: '5rem' }}>Your generated prompt will appear here...</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
